#%RAML 1.0
---
title: Assessment
version: v1

types:
  institution: !include schemas/institution.schema.json
  mainClass: !include schemas/main-class.schema.json
  materialType: !include schemas/material-type.schema.json

/assessment:
  /location-units:
    description: Collection of nested location units
    get:
      description: Get a list of nested location units
      responses:
        200:
          body:
            application/json:
              type: institution[]
              example: !include examples/location-units.example.json
        500:
          body:
            text/plain:
              example: Internal Server Error
  /collections-by-lcc-number:
    description: Collection of nested classifications, with collections counts
    get:
      description: Get a list of nested classifications, with collections counts
      responses:
        200:
          body:
            application/json:
              type: mainClass[]
              example: !include examples/collections-by-lcc-number.json
        500:
          body:
            text/plain:
              example: Internal Server Error
  /collections-by-material-type:
    description: Collection of material types, with collections counts
    get:
      description: Get a list of material types, with collections counts
      responses:
        200:
          body:
            application/json:
              type: materialType[]
              example: !include examples/collections-by-material-type.json
        500:
          body:
            text/plain:
              example: Internal Server Error
  /circulation-by-material-type:
    description: Collection of material types, with circulation counts
    get:
      description: Get a list of material types, with circulation counts
      queryParameters:
        from:
          displayName: From
          type: date-only
          description: The lower bound of the date range
          example: 2010-01-01
          required: true
        to:
          displayName: To
          type: date-only
          description: The upper bound of the date range
          example: 2019-12-31
          required: true

      responses:
        200:
          body:
            application/json:
              type: materialType[]
              example: !include examples/circulation-by-material-type.json
        400:
          body:
            text/plain:
              example: Missing query parameter(s)
        500:
          body:
            text/plain:
              example: Internal Server Error
